### ISSUE TITLE
UCT implementation underweights exploration by 1-2 orders of magnitude

### ISSUE THREAD

**Issue by smallnamespace** [Ragowit/fireplace#50]
@Ragowit 

Here you've defined payoff as https://github.com/Ragowit/fireplace/blob/master/mcts/uct.py#L265

In all the MCTS/UCT papers, payoff is usually bounded on the range `[-1, 1]`. Multiplying the payoff by ~100 or so leads this implementation almost never exploring an unvisited node, but rather always further exploring the highest-payoff subtree. Just hope you're aware of this.

**Comment by Ragowit** [comment]
Thanks for your input!

My idea when I wrote that line was to make sure to never miss a turn with lethal. Winning a game sooner should result in a higher score, that was what I was thinking.

**Comment by smallnamespace** [comment]
If that's your goal, I suggest you do it through discounting:

`discounted_payoff = payoff * math.pow(discount_factor, turn)`

where `discount_factor` is something slightly less than 1.

**Comment by Ragowit** [comment]
Solved with 62d3baa.
